@url=http://localhost:3000

### list
GET {{url}}/api/books

### search with header
GET {{url}}/api/books?q=1
Authorization: Bearer xxx
user-agent: Soo

### 
POST {{url}}/api/books

{
    "title": "Book Title",
    "writer": "jade",
}

###
PATCH  {{url}}/api/books/3

{
    "title":"new title"
}

### 

DELETE {{url}}/api/books/1